### ISSUE TITLE
gitreflow doesn't seem to work with 2FA on GitHub

### ISSUE THREAD

**Issue by cezaraugusto** [reenhanced/gitreflow#248]
Hello there! I'm trying to use gitreflow w/ 2FA turned on, but getting an error after `git reflow setup`.

<details>
<summary>Stack trace</summary>

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /Users/cezar in PATH, mode 040777
Available remote Git Server services:
1. GitHub
2. BitBucket (team-owned repos only)
Which service would you like to use for this project?  1
Please enter your GitHub password (we do NOT store this): 
EXECUTED: get - /authorizations with PARAMS: {}
"Connection options : \n"
{:headers=>
  {"Accept"=>
    "application/vnd.github.v3+json,application/vnd.github.beta+json;q=0.5,application/json;q=0.1",
   "Accept-Charset"=>"utf-8",
   "User-Agent"=>"Github API Ruby Gem 0.19.0"},
 :ssl=>
  {:ca_file=>
    "/Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/ssl_certs/cacerts.pem"},
 :url=>"https://api.github.com",
 :builder=>
  #<Faraday::RackBuilder:0x00007fc7c6b6e5c8
   @adapter=Faraday::Adapter::NetHttp,
   @handlers=
    [Github::Request::Jsonize,
     Faraday::Request::Multipart,
     Faraday::Request::UrlEncoded,
     Github::Request::BasicAuth,
     Github::Response::FollowRedirects,
     Faraday::Response::Logger,
     Github::Response::Mashify,
     Github::Response::Jsonize,
     Github::Response::AtomParser,
     Github::Response::RaiseError]>}
I, [2021-03-12T13:47:11.444245 #68621]  INFO -- request: GET https://api.github.com/authorizations
I, [2021-03-12T13:47:11.444334 #68621]  INFO -- request: Accept: "application/vnd.github.v3+json,application/vnd.github.beta+json;q=0.5,application/json;q=0.1"
Accept-Charset: "utf-8"
User-Agent: "Github API Ruby Gem 0.19.0"
Authorization: "Basic Y2V6YXJhdWd1c3RvOnBoKzQ4ZT11dGhhZGVodWN1cXVaQXA4Jg=="
Traceback (most recent call last):
        43: from /usr/local/bin/git-reflow:23:in `<main>'
        42: from /usr/local/bin/git-reflow:23:in `load'
        41: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/exe/git-reflow:19:in `<top (required)>'
        40: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/exe/git-reflow:19:in `public_send'
        39: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow.rb:52:in `method_missing'
        38: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/workflow.rb:184:in `block in command'
        37: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/workflows/core.rb:47:in `block in <class:Core>'
        36: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `choose'
        35: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `choose'
        34: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline.rb:277:in `choose'
        33: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline/menu.rb:415:in `select'
        32: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline/menu.rb:449:in `value_for_selected_item'
        31: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/workflows/core.rb:51:in `block (3 levels) in <class:Core>'
        30: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/git_server.rb:17:in `connect'
        29: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/git_server/git_hub.rb:119:in `authenticate'
        28: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/api.rb:209:in `block in method_added'
        27: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/api.rb:249:in `execute'
        26: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/api.rb:237:in `run_callbacks'
        25: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/api.rb:250:in `block in execute'
        24: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/api.rb:209:in `block in method_added'
        23: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/api.rb:249:in `execute'
        22: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/api.rb:237:in `run_callbacks'
        21: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/api.rb:250:in `block in execute'
        20: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/client/authorizations.rb:28:in `list'
        19: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/request/verbs.rb:23:in `get_request'
        18: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/request.rb:68:in `call'
        17: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/connection.rb:198:in `get'
        16: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
        15: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
        14: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/request/jsonize.rb:23:in `call'
        13: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/request/multipart.rb:30:in `call'
        12: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/request/url_encoded.rb:25:in `call'
        11: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/request/basic_auth.rb:32:in `call'
        10: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/response/follow_redirects.rb:72:in `call'
         9: from /Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/response/follow_redirects.rb:84:in `perform_with_redirection'
         8: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/response/logger.rb:25:in `call'
         7: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
         6: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
         5: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
         4: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
         3: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
         2: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/response.rb:59:in `on_complete'
         1: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:19:in `block in call'
/Library/Ruby/Gems/2.6.0/gems/github_api-0.19.0/lib/github_api/response/raise_error.rb:19:in `on_complete': GET https://api.github.com/authorizations: 404 - Not Found (Github::Error::NotFound)
See: https://docs.github.com/rest
        15: from /usr/local/bin/git-reflow:23:in `<main>'
        14: from /usr/local/bin/git-reflow:23:in `load'
        13: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/exe/git-reflow:19:in `<top (required)>'
        12: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/exe/git-reflow:19:in `public_send'
        11: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow.rb:52:in `method_missing'
        10: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/workflow.rb:184:in `block in command'
         9: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/workflows/core.rb:47:in `block in <class:Core>'
         8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `choose'
         7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `choose'
         6: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline.rb:277:in `choose'
         5: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline/menu.rb:415:in `select'
         4: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline/menu.rb:449:in `value_for_selected_item'
         3: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/workflows/core.rb:51:in `block (3 levels) in <class:Core>'
         2: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/git_server.rb:17:in `connect'
         1: from /Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/git_server/git_hub.rb:107:in `authenticate'
/Library/Ruby/Gems/2.6.0/gems/git_reflow-0.9.4/lib/git_reflow/git_server/git_hub.rb:146:in `rescue in authenticate': We were unable to authenticate with Github. (RuntimeError)
```
</details>

**Comment by codenamev** [comment]
A workaround was found for this in #250.  We'll be dropping support for generating access tokens from our CLI.  Feel free to track the progress of this in #250.
