### ISSUE TITLE
f has already been specified as a switch in the command deliver (ArgumentError)

### ISSUE THREAD

**Issue by ivdma** [reenhanced/gitreflow#59]
Just installed git reflow with

    gem install reflow

on OS X Mavericks with rbenv 0.4.0 and Ruby 2.1.0-p0 (also tried with 2.0.0-p353). I keep getting the following error:

    ~/code/project » git reflow                                                                                                                              
    /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/dsl.rb:203:in `verify_unused_in_option': f has already been specified as a switch in the command deliver (ArgumentError)
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/dsl.rb:197:in `block in verify_unused'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/dsl.rb:195:in `each'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/dsl.rb:195:in `verify_unused'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/dsl.rb:97:in `switch'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/command_support.rb:73:in `switch'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git_reflow-0.3.4/lib/git_reflow/commands/deliver.rb:6:in `block in <top (required)>'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/dsl.rb:177:in `command'
	from /usr/local/Cellar/rbenv/0.4.0/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git_reflow-0.3.4/lib/git_reflow/commands/deliver.rb:4:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:114:in `require'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:114:in `require'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/app.rb:280:in `block in load_commands'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/app.rb:277:in `each'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/app.rb:277:in `load_commands'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/app.rb:38:in `block in commands_from'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/app.rb:36:in `each'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/gli-2.8.1/lib/gli/app.rb:36:in `commands_from'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git_reflow-0.3.4/bin/git-reflow:24:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/bin/git-reflow:23:in `load'
	from /usr/local/opt/rbenv/versions/2.0.0-p353/bin/git-reflow:23:in `<main>'

I chased Google to find the answer, but got nothing. Any ideas?

P.S. This is probably something GLI-related?

**Comment by axtl** [comment]
Using ruby 2.3.0 and git_reflow 0.8.1 (and git 2.8.3) on OS X 10.11.5, I get:

```
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/dsl.rb:227:in `verify_unused_in_option': f has already been specified as a switch in the command deliver (ArgumentError)
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/dsl.rb:221:in `block in verify_unused'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/dsl.rb:219:in `each'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/dsl.rb:219:in `verify_unused'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/dsl.rb:118:in `switch'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/command_support.rb:78:in `switch'
        from /usr/local/Cellar/rbenv/1.0.0/versions/2.3.0/lib/ruby/gems/2.3.0/gems/git_reflow-0.8.1/lib/git_reflow/commands/deliver.rb:6:in `block in <top (required)>'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/dsl.rb:200:in `command'
        from /usr/local/Cellar/rbenv/1.0.0/versions/2.3.0/lib/ruby/gems/2.3.0/gems/git_reflow-0.8.1/lib/git_reflow/commands/deliver.rb:4:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/app.rb:324:in `block in load_commands'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/app.rb:321:in `each'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/app.rb:321:in `load_commands'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/app.rb:38:in `block in commands_from'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/app.rb:36:in `each'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/app.rb:36:in `commands_from'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/git_reflow-0.8.1/exe/git-reflow:13:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.3.0/bin/git-reflow:23:in `load'
        from /usr/local/opt/rbenv/versions/2.3.0/bin/git-reflow:23:in `<main>'
```

Also tried on 2.2.5 and 2.3.1 with the same error.

**Comment by codenamev** [comment]
I will investigate on my next deliver.

**Comment by pushcx** [comment]
It's a bug caused by the command files being double-included. GLI sees that it's ordered to define a switch for a command (in this case, deliver) that is already used and bombs out.

`exe/git-reflow` adds its lib dir to $LOAD_PATH and calls `commands_from 'git_reflow/commands'`. GLI (`commands_from` in `lib/gli/app.rb`) expects to be passed a path that returns true to `Pathname.new(path).absolute? and File.exist?(path)`. Both sides of the predicate return `false`.

So `commands_from` silently ignores the path and walks every entry in`$LOAD_PATH` looking for commands. If someone's `$LOAD_PATH` already included the git-reflow directory (quirk of gem version? I dunno), the commands are included twice and fail.

git-reflow could workaround by not including itself on the $LOAD_PATH if it's already there, or kick it upstream to GLI's `command_from` to not silently replace arguments with arbitrary global variables (*srsly*) and/or idempotently define commands.

**Comment by pushcx** [comment]
I think the double-loading is happening if the gem dir is a symlink. The same files can appear twice under two apparently different paths.

**Comment by codenamev** [comment]
@pushcx I've been unable to reproduce this locally.  While you have this failing, can you try opening up the gem locally and seeing if removing the line that adds the lib dir to the `$LOAD_PATH` fixes the issue?

**Comment by pushcx** [comment]
It does not fix it. It's the symlink thing.

I think you can probably reproduce this by setting one up. Run `gem env` to see your "USER INSTALLATION DIRECTORY", then run `ln -s ~/gemhome [USER INSTALL DIR]` to set up a symlink and `export GEM_HOME="~/gemhome"` to tell gem to use it (maybe also set GEM_PATH similarly?). Then `git reflow setup` should fail with this error.

**Comment by ivdma** [comment]
I installed a fresh macOS Sierra. 
Running rbenv with globally defined ruby 2.3.1.
I updated Rubygems to 2.6.6
and then `gem install git_reflow`-ed

Getting the same error again.
